[project]
name = "wanikani-tui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ferjjp", email = "fer.jjp@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "jeepney>=0.9.0; sys_platform == 'linux'",
    "pillow>=12.3.0",
    "resvg-py>=0.5.0",
    "textual>=8.2.8",
    "textual-image>=0.13.2",
    "wanakana-python>=1.2.2",
]

[project.scripts]
wk = "wanikani_tui.cli:main"

[build-system]
requires = ["uv_build>=0.11.8,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
